triggers:
- description: null
  envs: []
  last_enabled_at: 2025-01-25 15:16:39.537848
  name: weekly_load_real_estate_data
  pipeline_uuid: real_estate
  schedule_interval: '@weekly'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2025-01-12 05:00:00
  status: active
  token: ${SLACK_TRIGGER_TOKEN}
  variables: {}
