version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zoomcamp
      POSTGRES_DB: mage_db
    volumes:
      - pg_data:/var/lib/postgresql/data

  mageai:
    build:
      context: .
      dockerfile: dockerfile  # Ensure this path is correct
    ports:
      - "6789:6789"
    volumes:
      - ./mage_data:/home/src
      - ./secrets:/home/src/secrets
      - ./.env:/home/src/.env
    env_file:
      - .env
    environment:
      - MAGE_PROJECT=de-zoomcamp-project
    command: ["mage", "start", "de-zoomcamp-project"]

  dbt:
    build:
      context: .
      dockerfile: dockerfile  # Ensure this path is correct
    container_name: dbt
    volumes:
      - ./dbt_zoomcamp:/usr/app/dbt
      - ./dbt_zoomcamp/dbt_cloud.yml:/root/.dbt/dbt_cloud.yml
    working_dir: /usr/app/dbt
    environment:
      - DBT_PROFILES_DIR=/usr/app/dbt/profiles
    command: ["dbt", "run"]


volumes:
  pg_data: