version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: mage_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mageai:
    image: mageai/mageai:latest
    ports:
      - "6789:6789"
    volumes:
      - ./mage_data:/home/src
      - ./secrets:/home/src/secrets
      - ./.env:/home/src/.env
    env_file:
      - .env
    environment:
      - MAGE_PROJECT=de-zoomcamp-project
    command: ["mage", "start", "de-zoomcamp-project"]

volumes:
  postgres_data: