version: 2

sources:
  - name: staging
    database: "mage_db"
    schema: "public"

    tables:
      - name: real_estate_data
      - name: stats
      - name: real_estate_data_weekly
      - name: avg_price_per_sqm_by_city